# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: node-build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup environment
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          check-latest: true

      # Caches
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}

      # Install
      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline

      # Code consistency
      - name: Lint
        run: npm run lint

      - name: Code Style
        run: npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: 'style: formatting'
          branch: ${{ github.head_ref }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup environment
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          check-latest: true

      # Caches
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}

      # Install
      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline

      # Test
      - name: Test
        run: npm run test